### ISSUE TITLE
Unknown Git Events

### ISSUE THREAD

**Issue by dargmuesli** [freifunkks/sopel-modules#2]
These events are currently unknown:

- deployment
- deployment_status
- fork
- member
- page_build
- pull_request_review
- pull_request_review_comment
- repository_vulnerability_alert
- star
- team
- team_add
- watch

**Comment by flxai** [comment]
This is correct. PRs are very welcome.

**Comment by nikeee** [comment]
As of https://github.com/freifunkks/sopel-modules/pull/3/files, the first two are now ignored/skipped.

**Comment by dargmuesli** [comment]
All of them?

**Comment by nikeee** [comment]
The first two, namely `deployment` and `deployment_status` (as stated in the referred PR).
`page_build` is also supported as of this PR.

**Comment by dargmuesli** [comment]
Now someone has to find out where and how to update @flipdot's bot 😂
